BLK_DAESS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django .conf.urls. static import static
from django .conf import settings
#from myco import views
from django.views.static import serve
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("index.urls")),
    path('account/',include("account.urls")),
    path('event/',include('event.urls')),
    path('products/',include('products.urls')),
    path('donation/',include('donation.urls')),
    path('publications/',include('publications.urls')),
    path('achievement/',include('achievement.urls')),
    path('career/',include("career.urls")),
    path('project/',include("project.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
   
]

#handler404 = views.error_404
#handler500 = views.error_500


urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
     
     path('Login/',views.Login,name="account"),
     path('Logout/',views.Logout,name="logout"),
     path('dashboard/',views.dashboard,name="dashboard"),
     path('PartinersForm/',views.Partiners,name="Partiners"),
     path('Team/',views.teamMember,name="TeamMember"),
     path('editTeam/<slug>/',views.EditTeam,name="EditTeam"),
     path('removemember/<int:id>/',views.removemember,name="removemember"),
     #path('register_view/',views.register_view,name="register_view")
   
    
]

donation/urls.py
from . import views
from django.urls import path

app_name = "give"

urlpatterns = [
     path('donation/',views.donation,name="donation"),
     path('mpamba/',views.mpamba,name="mpamba"),
     path('mpamba2/',views.mpamba2,name="mpamba2"),
     path('airtelmoney/',views.airtelmoney,name="airtelmoney"),
     path('airtelmoney2/',views.airtelmoney2,name="airtelmoney2"),
     path('donation_thax/',views.donation_thax,name="donation_thax"),
     path('donation_thax2/',views.donation_thax2,name="donation_thax2"),
     path('donation_view/',views.donation_view,name="donation_view")
]

event/urls.py
from . import views
from django.urls import path

app_name = "event"

urlpatterns = [
     path('event/',views.event,name="event"),
     path('eventasp/<asp>/',views.event,name="event2"),
     path('event_detail/<slug>/',views.event_detail,name="event_detail"),
     path('event_form/',views.event_form,name="event_form"),
     path('document_view/',views.document_view,name="document_view"),
     path('DocuForm/',views.DocuForm,name="DocuForm"),
     path('Editevent/<int:id>/',views.Editevent,name="Editevent"),
     path('RemoveEvent/<int:id>/',views.RemoveEvent,name="RemoveEvent"),
     path('document_detail/<int:id>/',views.document_detail,name="document_detail")  
]

index/urls.py
from . import views
from django.urls import path

app_name = "index"

urlpatterns = [
     
     path('',views.index,name="index"),
     path('about_daess/',views.about_daess,name="about_daess"),
     path('contact/',views.contact,name="contact"),
     path('DaessoBjectives/',views.daess_objectives,name="objective"),
     path('DaessStructure/',views.daess_structure,name="structure"),
     path('team/',views.team,name="team"),
     path('team2/<args>/',views.team,name="team2"),
     path('ASP/<asp>/',views.ASP,name="ASP"),
     path('Subscribe/',views.Subscribe,name="Subscribe"),
     path('unsubscribe/',views.unsubscribe,name="unsubscribe"),
     path('team_detail/<slug>/',views.tema_detail,name="tema_detail")
]

donation/models.py
from django.db import models

class DAESS_Donation(models.Model):
	name = models.CharField(max_length=100)
	email =models.EmailField(blank=True)
	phone = models.CharField(max_length=100,blank=True)
	ref  = models.CharField(max_length=100,blank=True)
	amount = models.PositiveIntegerField(null=True,blank=True)
	verified = models.BooleanField(default=False)
	paypal = models.BooleanField(default=True)
	created_at     = models.DateTimeField(auto_now_add=True,null=True,blank=True)

	def __str__(self):
		return self.name

donation/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm
from django.http import HttpResponse,JsonResponse
from django.template.loader import render_to_string
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from index.snipt import secret_code
from.models import DAESS_Donation


def donation_fuc(request,item,context):
	if request.session.has_key('q'):
		quer = request.session['q']
		item = item.filter(Q(name__icontains=quer)| 
			               Q(phone__icontains=quer)|
			               Q(email__icontains=quer)|
			               Q(ref__icontains=quer)).distinct()
		del request.session['q']

	query =request.GET.get('q')
	if query:
		item =item.filter(Q(name__icontains=query)|
		                  Q(phone__icontains=query)|
		                  Q(email__icontains=query)| 
			              Q(ref__icontains=query)).distinct()


	page = request.GET.get('page', 1)
	paginator = Paginator(item,20)

	try:
		item = paginator.page(page)
	except PageNotAnInteger:
		item = paginator.page(1)
	except EmptyPage:
		item = paginator.page(paginator.num_pages)

	context['give'] = item

def donation(request):

	context = {}
	context['title']="Donate"

	if request.is_ajax():
		Email = request.GET.get('email')
		Name= request.GET.get('dzina')
		Amount= request.GET.get('amount')

		give = DAESS_Donation(name=Name,email=Email,amount=Amount,ref=secret_code())
		give.save()

		request.session['email'] = Email

		host = request.get_host()
		paypal_dict ={'business': settings.PAYPAL_RECEIVER_EMAIL,
                      'amount':Amount,
                      'item_name': 'donation',
                      'invoice':secret_code(),
                      'currency_code': 'USD',
                      'notify_url': 'http://{}{}'.format(host, reverse('paypal-ipn')),
                      'return_url': 'http://{}{}'.format(host, reverse('give:donation_thax')),
                      'cancel_return': 'http://{}{}'.format(host, reverse('give:donation')),}
		paypal_form= PayPalPaymentsForm(initial=paypal_dict,button_type="donate")


		

		context['paypal_form'] = paypal_form
		context['name'] = Name
		context['amount'] = Amount

		html = render_to_string('donation/paypal_btn.html',context,request=request)
		return JsonResponse({'data':html})

	return render(request,"donation/give.html",context)

def mpamba(request):
	context = {}

	if request.is_ajax():
		html = render_to_string('donation/mpamba.html',context,request=request)
		return JsonResponse({'data':html})

def mpamba2(request):
	if request.method =='GET':

		Email = request.GET.get('email')
		Name= request.GET.get('dzina')
		Amount= request.GET.get('amount')
		Ref = request.GET.get('ref')
		Phone = request.GET.get('phone')

		give = DAESS_Donation(name=Name,phone=Phone,paypal=False,email=Email,amount=Amount,ref=Ref)
		give.save()

		request.session['email'] = Email

		return redirect('give:donation_thax2')



def airtelmoney(request):
	context = {}

	if request.is_ajax():
		html = render_to_string('donation/airtelmoney.html',context,request=request)
		return JsonResponse({'data':html})


def airtelmoney2(request):
	if request.method =='GET':
		
		Email = request.GET.get('email')
		Name= request.GET.get('dzina')
		Amount= request.GET.get('amount')
		Ref = request.GET.get('ref')
		Phone = request.GET.get('phone')

		give = DAESS_Donation(name=Name,phone=Phone,paypal=False,email=Email,amount=Amount,ref=Ref)
		give.save()

		request.session['email'] = Email

		return redirect('give:donation_thax2')


def donation_thax(request):
	context = {}

	if request.session.has_key('email'):
		Email = request.session['email']


		give = DAESS_Donation.objects.filter(email=Email).last()
		give.verified = True
		give.save()

		context['donar'] = give
		
		del request.session['email']

	return render(request,"donation/thax.html",context)

def donation_thax2(request):
	context = {}

	if request.session.has_key('email'):
		Email = request.session['email']


		give = DAESS_Donation.objects.filter(email=Email).last()
		give.save()

		context['donar'] = give
		
	return render(request,"donation/thax2.html",context)

@login_required(login_url="account:account")
def donation_view(request):
	context = {}

	context['search'] = "Search donar"

	item = DAESS_Donation.objects.all().order_by('-id')
	donation_fuc(request,item,context)

	if request.is_ajax():
		id = request.GET.get('id');

		item2 = DAESS_Donation.objects.get(id=id)
		item2.verified = True
		item2.save()

		item = DAESS_Donation.objects.all().order_by('-id')
		donation_fuc(request,item,context)
		
		html = render_to_string('donation/donation_view2.html',context,request=request)
		return JsonResponse({'data':html})

	return render(request,"donation/donation_view.html",context)

donation/templates/donation/airtelmoney.html
{% load static %}
<div class="text-center">
                  <div class="text-left">
                    <h4><img src="{% static 'img/airtelmoney.jpg' %}" class="rounded mr-2" height="20">Airtel Money</h4>
                    <ul>
                       <li>Dial *211#</li>
                       <li>Select 2 for send money</li>
                       <li>Select 1 for Airtel Number</li>
                       <li>Select 1 for number then enter the phone number (DAESS number).</li>
                    </ul>
                    <p>Using the reference number/transaction number of the payment mediums above kindly complete the form below.</p>
                  </div>
                  <form id="donate_form" action="{% url 'give:airtelmoney2'%}">
                      {% csrf_token %}
                     <label>Full name</label>
                     <input type="text" name="dzina">
                     <label>Email</label>
                     <input type="email" name="email">
                     <label>Phone number</label>
                     <input type="number" name="phone">
                     <label>Payment Reference Number</label>
                     <input type="text" name="ref">
                     <label>Amount(USD)</label>
                     <input type="number" name="amount">
                     <button class="my-4" id="custom_btn">Submit</button>
                  </form>

                  <div class="text-left">
                     <a id="airtel_btn" class="mr-4" href="{%url 'give:donation'%}">Paypal</a>
                  </div>
              </div>

donation/templates/donation/donation_view.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section style="background:url({% static 'img/ddn.jpg'%});background-repeat: no-repeat;background-position: center center;
  background-size: cover;background-attachment: fixed;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a>
          <a href="javascripts:void(0);">/</a>
          <a href="{% url 'account:dashboard' %}">Dashboard</a> 
          <a href="javascripts:void(0);">/</a>
          <a href="#">Donation</a>
          <hr>
          <h4>Donation received</h4>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>

<section class="my-2">
     <div class="container">
         <div class="row">
              <div class="col-sm-12 col-lg-12  my-2 table-responsive">
                   <div id="donation_view">
                  
                    <div class="p-2 rounded">
                       <table class="table table-striped ">
                          <thead style="background-color:rgb(0,0,153);color:white;">
                             <tr>
                             <th>Name</th>
                             <th>Amount</th>
                             <th>Ref code</th>
                             <th>Phone</th>
                             <th>Email</th>
                          </tr>
                          </thead>
                          {% for give in give %}
                          <tr> 
                              <td>{{give}}<br>
                              {% if give.paypal == True %}
                                 <small style="color:green;">paypal</small>
                              {% else %}
                                 <small style="color:green;">Mobile money |
                                     {% if give.verified == True %}
                                       Verified
                                       <i class="fa fa-check" aria-hidden="true"></i>
                                     {% else %}
                                       <a accesskey="{{give.id}}" id="verify_give" href="javascript:void(0);">Verify</a>
                                     {% endif %}
                                 </small>
                              {% endif %}
                             </td>
                             {% if give.paypal == True %}
                              <td>$ {{give.amount}}</td>
                              {% else %}
                              <td>Mk {{give.amount}}</td>
                              {% endif %}
                              <td>{{give.ref}}</td>
                              <td>{{give.phone}}</td>
                              <td>{{give.email}}</td>
                          </tr>
                          {% empty %}
                          <tr>
                             <td colspan="5">No donation found !!!</td>
                          </tr>
                          {% endfor %}
                       </table>
                    </div>
                  
                </div>
                  <!--_______________________pagination_________________________________-->
           <div class="col-sm-12 my-2">
               <div class="pagination">
                <span class="step-links">
                    {% if give.has_previous %}
                        <a href="?page=1">&laquo;</a>
                        <a href="?page={{give.previous_page_number }}">
                          <i class="fa fa-arrow-left" aria-hidden="true"></i>
                        </a>

                    {% endif %}

                    <span class="current">
                        Page {{give.number }} of {{give.paginator.num_pages }}.
                    </span>

                    {% if give.has_next %}
                        <a href="?page={{give.next_page_number }}">
                          <i class="fa fa-arrow-right" aria-hidden="true"></i>
                        </a>
                        <a href="?page={{give.paginator.num_pages }}">&raquo;</a>
                    {% endif %}
                </span>
            </div>
           </div>
<!--__________________________________________________________________-->
              </div>
         </div>
     </div>
</section>

{% endblock %}

donation/templates/donation/donation_view2.html
   <div id="donation_view">
                  
                    <div class="p-2 rounded">
                       <table class="table table-striped">
                          <thead style="background-color:rgb(0,0,153);color:white;">
                             <tr>
                             <th>Name</th>
                             <th>Amount</th>
                             <th>Ref code</th>
                             <th>Phone</th>
                             <th>Email</th>
                          </tr>
                          </thead>
                          {% for give in give %}
                          <tr> 
                              <td>{{give}}<br>
                              {% if give.paypal == True %}
                                 <small style="color:green;">paypal
                                  <i class="fa fa-check" aria-hidden="true"></i>
                                 </small>
                              {% else %}
                                 <small style="color:green;">Mobile money |
                                     {% if give.verified == True %}
                                       Verified
                                       <i class="fa fa-check" aria-hidden="true"></i>
                                     {% else %}
                                       <a accesskey="{{give.id}}" id="verify_give" href="javascript:void(0);">Verify</a>
                                     {% endif %}
                                 </small>
                              {% endif %}
                             </td>
                              {% if give.paypal == True %}
                              <td>$ {{give.amount}}</td>
                              {% else %}
                              <td>Mk {{give.amount}}</td>
                              {% endif %}
                              <td>{{give.ref}}</td>
                              <td>{{give.phone}}</td>
                              <td>{{give.email}}</td>
                          </tr>
                          {% empty %}
                          <tr>
                             <td colspan="5">No donation found !!!</td>
                          </tr>
                          {% endfor %}
                       </table>
                    </div>
                  
                </div>

donation/templates/donation/give.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section class="animatedParent"  style="background:url({% static 'img/ddn.jpg'%});background-repeat: no-repeat;background-position: center center;background-size:cover;background-attachment:fixed;height:90vh;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="#">Donate</a>
          <hr>
          <div  style="padding-bottom:200px;padding-top:100px;">
             <div>
                <h1 class="animated bounceInRight" style="color:white;"><strong >Make a difference !!</strong></h1>
                <h2 class="animated bounceInLeft" style="color:rgb(0,0,153);"><strong>Donate now</strong></h2>
             </div>
             <div class="text-center animated bounceInDown">
                <a class="" href="#donate">
                   <img src="{% static 'img/b_arrow.png' %}" height="50">
                </a>
             </div>
          </div>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>

<section class="my-2 donate">
   <div class="container">
       <div class="row">
           <div class="col-sm-12 col-lg-4">
               
           </div>
           <div class="col-sm-12 col-lg-4">
<!-------------------------------paypal form-------------------------->
               <div  class="text-center paypal" id="paypal_btn_area"><a name="donate"></a>

                  <form id="donate_form" action="{% url 'give:donation'%}">
                      {% csrf_token %}
                     <label>Full name</label>
                     <input type="text" name="dzina">
                     <label>Email</label>
                     <input type="email" name="email">
                     <label>Amount(USD)</label>
                     <input type="number" name="amount">
                     <button class="my-4" id="custom_btn">Continue to paypal</button>
                  </form>

                  <div class="">
                     <a id="airtel_btn" class="mr-4" href="javascript:void(0);">Airtel money</a>
                     <a id="mpamba_btn" href="javascript:void(0);">Mpamba</a>
                  </div>

               </div>
           </div>
       </div>
   </div>
</section>
{% endblock %}

donation/templates/donation/mpamba.html
{% load static %}
<div>
                  <div class="text-left">
                
                    <h4><img src="{% static 'img/mpamba.jpg' %}" class="rounded" height="30">TNM Mpamba</h4>
                    <ul>
                       <li>Dial *444#</li>
                       <li>Select 1 for send money</li>
                       <li>Select 1 for TNM Mpamba</li>
                       <li>Select 1 for send to wallet then enter the phone number (DAESS number).</li>
                    </ul>
                    <p>Using the reference number/transaction number of the payment mediums above kindly complete the form below.</p>
                  </div>
                  <form id="donate_form" action="{% url 'give:mpamba2'%}">
                      {% csrf_token %}
                     <label>Full name</label>
                     <input type="text" name="dzina">
                     <label>Email</label>
                     <input type="email" name="email">
                     <label>Phone number</label>
                     <input type="number" name="phone">
                     <label>Payment Reference Number</label>
                     <input type="text" name="ref">
                     <label>Amount(USD)</label>
                     <input type="number" name="amount">
                     <button class="my-4" id="custom_btn">Submit</button>
                  </form>

                  <div class="text-left">
                     <a id="mpamba_btn" href="{%url 'give:donation'%}">Paypal</a>
                  </div>
              </div>

donation/templates/donation/paypal_btn.html
<!-------------------------------paypal btn------------------------------->
<div class="mb-4">
    <div class="row">

        <div class="col-sm-12 col-lg-2">
            <!----pass----->
        </div>

        <div class="col-sm-12 col-lg-8">
            <p><strong>{{name}} your donating ${{amount}}</strong></p><hr>
            {{paypal_form.render}}              
        </div>

        <div class="col-sm-12 col-lg-2">
            <!----pass----->
        </div>

    </div>
</div>

donation/templates/donation/thax.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section style="background:url({% static 'img/ddn.jpg'%});background-repeat: no-repeat;background-position: center center;
  background-size: cover;background-attachment: fixed;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="give:donation">Donate</a>
          <hr>
          <h4>Give</h4>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>

<section class="my-2 donate">
   <div class="container">
       <div class="row">
          <div class="col-sm-12 col-lg-4">
           <!--------------pass------------------->
          </div>

          <div class="col-sm-12 col-lg-4 text-center p-4 mx-2 rounded" style="background:#f2f2f2;">
           <img src="{% static 'img/thank.png' %}" height="100">
           <p>Thanks for your donation <span style="color:green;">{{donar}}</span></p>
           <h4> Your more than kind !!</h4>
           <a id="custom_btn" href="{% url 'index:index' %}">Go home</a>
          </div>
       </div>
   </div>
</section>
{% endblock %}

donation/templates/donation/thax2.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section style="background:url({% static 'img/ddn.jpg'%});background-repeat: no-repeat;background-position: center center;
  background-size: cover;background-attachment: fixed;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="give:donation">Donate</a>
          <hr>
          <h4>Give</h4>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>

<section class="my-2 donate">
   <div class="container">
       <div class="row">
          <div class="col-sm-12 col-lg-4">
           <!--------------pass------------------->
          </div>

          <div class="col-sm-12 col-lg-4 text-center p-4 mx-2 rounded" style="background:#f2f2f2;">
           <img src="{% static 'img/thank.png' %}" height="100">
           
           <p>Thanks for your donation <span style="color:green;">{{donar}}</span></p>
           <h4> Your more than kind !!</h4>
           <hr>
           <p style="color:red;">Your donation will be verified soon</p>

           <a id="custom_btn" href="{% url 'index:index' %}">Go home</a>
          </div>
       </div>
   </div>
</section>
{% endblock %}