BLK_DAESS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django .conf.urls. static import static
from django .conf import settings
#from myco import views
from django.views.static import serve
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("index.urls")),
    path('account/',include("account.urls")),
    path('event/',include('event.urls')),
    path('products/',include('products.urls')),
    path('donation/',include('donation.urls')),
    path('publications/',include('publications.urls')),
    path('achievement/',include('achievement.urls')),
    path('career/',include("career.urls")),
    path('project/',include("project.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
   
]

#handler404 = views.error_404
#handler500 = views.error_500


urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from . import views
from django.urls import path

app_name = "event"

urlpatterns = [
     path('event/',views.event,name="event"),
     path('eventasp/<asp>/',views.event,name="event2"),
     path('event_detail/<slug>/',views.event_detail,name="event_detail"),
     path('event_form/',views.event_form,name="event_form"),
     path('document_view/',views.document_view,name="document_view"),
     path('DocuForm/',views.DocuForm,name="DocuForm"),
     path('Editevent/<int:id>/',views.Editevent,name="Editevent"),
     path('RemoveEvent/<int:id>/',views.RemoveEvent,name="RemoveEvent"),
     path('document_detail/<int:id>/',views.document_detail,name="document_detail")  
]

index/urls.py
from . import views
from django.urls import path

app_name = "index"

urlpatterns = [
     
     path('',views.index,name="index"),
     path('about_daess/',views.about_daess,name="about_daess"),
     path('contact/',views.contact,name="contact"),
     path('DaessoBjectives/',views.daess_objectives,name="objective"),
     path('DaessStructure/',views.daess_structure,name="structure"),
     path('team/',views.team,name="team"),
     path('team2/<args>/',views.team,name="team2"),
     path('ASP/<asp>/',views.ASP,name="ASP"),
     path('Subscribe/',views.Subscribe,name="Subscribe"),
     path('unsubscribe/',views.unsubscribe,name="unsubscribe"),
     path('team_detail/<slug>/',views.tema_detail,name="tema_detail")
]

project/urls.py
from . import views
from django.urls import path

app_name = "projects"

urlpatterns = [
     path('projects/',views.projects_view,name="projects"),
     path('projects2/<args>/',views.projects_view,name="projects2"),
     path('ProjectForm/',views.PjForm,name="PjForm"),
     path('PjDetail/<slug>/',views.PjDetail,name="PjDetail"),
     path('EditPj/<int:id>/',views.EditPj,name="EditPj"),
     path('removePj/<int:id>/',views.removePj,name="removePj"),
     path('pj_document_detail/<int:id>/',views.pj_document_detail,name="pj_document_detail")
]

project/models.py
from django.db import models
from django.utils.text import slugify
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import post_save,pre_save
from ckeditor.fields import RichTextField

class Projects(models.Model):

	LOCATION = (
		  ('Msamala','Msamala'),
		  ('Nkaya','Nkaya'),
		  ('Kachenga','Kachenga'),
		  ('Chanthunya','Chanthunya'),
		  ('Kalembo','Kalembo'),
		  ('Amidu','Amidu'),
		  ('Sawali','Sawali'),
		  ('Matola','Matola'),
		  ('Phalula','Phalula'),
		  ('Toleza','Toleza'),
		  ('Mpilisi','Mpilisi'),
		  ('Ulongwe','Ulongwe'),
		  ('Rivirivi','Rivirivi'),
		  ('Utale','Utale'),
	
		)
	name = models.CharField(max_length=200)
	NGO  = models.CharField(max_length=200,blank=True)
	area = models.CharField(max_length=200,blank=True,choices=LOCATION)
	areas = models.CharField(max_length=200,blank=True)
	PJ_link  =models.URLField(blank=True)
	body     =RichTextField()
	slug     = models.SlugField(unique=True,null=True)
	view     =models.PositiveIntegerField(default=0)
	docu     =models.FileField(upload_to="pj file",blank=True)
	image    =models.ImageField(upload_to='projects')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('projects:PjDetail',kwargs ={'slug':self.slug})


def create_slug(instance,new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    qs = Projects.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.first().id)
        return create_slug(instance,new_slug=new_slug)
    return slug

def pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_receiver,sender=Projects)

class item_statistic(models.Model):#recommedation model
    item = models.ForeignKey(Projects,on_delete=models.CASCADE,related_name="daess_item")
    ip_address = models.CharField(blank=True,max_length=1000)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "views"

@receiver(post_save,sender=item_statistic)
def add_to_statistic(sender,created,instance,**kwargs):
    if created:
        instance.item.view += 1
        instance.item.save()

project/forms.py
from . models import Projects
from django.contrib.auth.models import User
from django.forms import ModelForm
from ckeditor.widgets import CKEditorWidget
from PIL import Image
from django import forms
	
class PJForm(ModelForm):

    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        body = forms.CharField(widget=CKEditorWidget())
        model = Projects
        fields = ('name',
                  'NGO',
                  'area',
                  'areas',
                  'PJ_link',
                  'body',
                  'docu',
                  'image',
                  'x',
                  'y',
                  'width',
                  'height')
        labels ={'area':'Target area',
                  'areas':'If more than one target area (OPTIONAL)',
                  'pdf':'Progress report (OPTIONAL)',
                  'PJ_link':'Projects page link (OPTIONAL)',
                }
        widgets = {
            'areas': forms.TextInput(attrs={'placeholder': 'Separate area with comma e.g Amidu,Toleza,Sawali'}),
        }

    def save(self):
        photo = super(PJForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.image)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((1000, 500), Image.ANTIALIAS)
        resized_image.save(photo.image.path)

        return photo

project/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse,JsonResponse
from django.template.loader import render_to_string
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from . forms import PJForm
from . models import Projects,item_statistic
from account.models import partners
from index.snipt import ip_address




def projects_view(request,args=None):

	context = {}
	context['partners'] = partners.objects.all()

	context['pj_count'] = Projects.objects.all().count()


	if request.session.has_key('alert'):
		msg = request.session['alert']
		context['alert'] = msg 
		del request.session['alert']

	if args:
		item = Projects.objects.filter(area=args,areas=args).order_by('-id')
		context['title'] = args + "|projects"

	else:
		item = Projects.objects.all().order_by('-id')
		context['title'] = "Our projects"

	if request.session.has_key('q'):#session from pj detail
		quer = request.session['q']
		item = item.filter(Q(name__icontains=quer)|
		                     Q(area__icontains=quer)|
		                     Q(areas__icontains=quer)|
			                 Q(NGO__icontains=quer)).distinct()
		del request.session['q']

	query =request.GET.get('q')
	if query:
		item = item.filter(Q(name__icontains=query)|
		                     Q(area__icontains=query)|
		                     Q(areas__icontains=query)|
			                 Q(NGO__icontains=query)).distinct()


	page = request.GET.get('page', 1)
	paginator = Paginator(item,12)

	try:
		item = paginator.page(page)
	except PageNotAnInteger:
		item = paginator.page(1)
	except EmptyPage:
		item = paginator.page(paginator.num_pages)

	context['pj'] = item

	context['search'] = "Search projects"

	return render(request,'projects/projects.html',context)

def PjDetail(request,slug):
	context = {}

	context['title'] = "Project detail"

	context['search'] = "Search projects"
	context['pj_count'] = Projects.objects.all().count()

	context['partners'] = partners.objects.all()

	pj = Projects.objects.get(slug=slug)
	context['pj'] = pj

	item_statistic.objects.create(item=pj,ip_address=ip_address(request))

	pj_d = Projects.objects.all().order_by('-view')[:10]
	context['pj_d'] = pj_d

	query =request.GET.get('q')
	if query:
		request.session['q'] = query
		return redirect("projects:projects")

	return render(request,'projects/projects_detail.html',context)

@login_required(login_url="account:account")
def PjForm(request):

	context = {}

	context['title'] = "Add project"

	context['search'] = "Search projects"

	if request.method == "POST":
		form = PJForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			request.session['alert'] = "Added successefully"
			return redirect('projects:projects')
	else:
		form = PJForm()

	context['form'] = form

	query =request.GET.get('q')
	if query:
		request.session['q'] = query
		return redirect("projects:projects")

	return render(request,"index/form.html",context)

@login_required(login_url="account:account")
def EditPj(request, id):

	context = {}

	context['title'] = "Edit project"

	context['search'] = "Search projects"

	pj = Projects.objects.get(id=id)

	if request.method == "POST":
		form = PJForm(request.POST,request.FILES,instance=pj)
		if form.is_valid():
			form.save()
			request.session['alert'] = "Added successefully"
			return redirect('projects:projects')
	else:
		form = PJForm()

	context['form'] = form

	query =request.GET.get('q')
	if query:
		request.session['q'] = query
		return redirect("projects:projects")

	return render(request,"index/form.html",context)

def removePj(request,id):
	pj = Projects.objects.get(id=id)
	request.session['alert'] = "Removed successefully"
	pj.delete()
	return redirect ("projects:projects")

def pj_document_detail(request,id):

	context = {}

	context['title'] = "Documents detail"

	docu = Projects.objects.get(id=id)
	context['docu'] = docu

	return render(request,"event/document_detail.html",context)

project/templates/projects/projects.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section style="background:url({% static 'img/ddd.jpg'%});background-repeat: no-repeat;background-position: center center;
  background-size: cover;background-attachment: fixed;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="#">Projects</a>
          <hr>
          <div class="item_category">
             <div >
                <a href="javascripts:void(0)">FILTER</a>
             </div>
             <div class="item_content p-4 rounded">

                 <div class="row">
                    <div class="col-sm-12 col-lg-2">
                      <a href="{% url 'projects:projects2' 'Bazale'%}">Bazale</a>
                      <a href="{% url 'projects:projects2' 'Ulongwe'%}">Ulongwe</a>
                      <a href="{% url 'projects:projects2' 'Mpilisi'%}">Mpilisi</a>
                      <a href="{% url 'projects:projects2' 'Rivirivi'%}">Rivirivi</a>
                      <a href="{% url 'projects:projects2' 'Phalula'%}">Phalula</a>
                      
                </div>
                <div class="col-sm-12 col-lg-2">
                       <a href="{% url 'projects:projects2' 'Msamala'%}">Msamala</a>
                       <a href="{% url 'projects:projects2' 'Nkaya'%}">Nkaya</a>
                       <a href="{% url 'projects:projects2' 'Kachenga'%}">Kachenga</a>
                       <a href="{% url 'projects:projects2' 'Kachenga'%}">Chanthunya</a>
                       <a href="{% url 'projects:projects2' 'Kalembo'%}">Kalembo</a>
                    </div>

                    <div class="col-sm-12 col-lg-2">
                       <a href="{% url 'projects:projects2' 'Amidu'%}">Amidu</a>
                       <a href="{% url 'projects:projects2' 'Sawali'%}">Sawali</a>
                       <a href="{% url 'projects:projects2' 'Matola'%}">Matola</a>
                       <a href="{% url 'projects:projects2' 'Toleza'%}">Toleza</a>
                       <a href="{% url 'projects:projects2' 'Utale'%}">Utale</a>
                    </div>
                    <div class="col-sm-12 col-lg-4">
                       <h4 style="color:black;"><span>Almost </span>{{pj_count}} projects are being implemented in Balaka</h4>
                    </div>
                 </div>
             </div>
          </div>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>


<section class="my-4">
   <div class="container">

       {% if alert %}
         <div id="alert" class="alert">
            <button type="button" data-dismiss="alert" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </button>
            <p style="color:rgb(0,128,0);">{{alert}}</p>
         </div>
        {% endif %}

       <div class="row animatedParent">
           {% for pj in pj %}
           <div class="col-sm-12 col-lg-6 animated fadeInUp">
               <div class="p-2">

                  {% if request.user.is_authenticated %}
                     <div id="daess_edit">
                        <a style="color:white;" href="{% url 'projects:EditPj' pj.id %}"><i class="fas fa-user-edit"></i></a>
                        <a style="color:white;" href="{% url 'projects:removePj' pj.id %}"><i class="fas fa-trash-alt"></i></a>
                     </div>
                     {% endif %}
                  
                  <a href="{% url 'projects:PjDetail' pj.slug %}">
                    {% if pj.image %}
                    <img src="{{pj.image.url}}" class="img-fluid rounded">
                    {% else %}
                    <img src="{% static 'img/blk2.png' %}" class="img-fluid rounded">
                    {% endif %}
                  </a>
                  <h4>{{pj}}</h4>
               </div>
           </div>
           {% empty %}
           <div class="col-sm-12">
              {% include 'index/error.html'%}
           </div>
           {% endfor %}
<!--_______________________pagination_________________________________-->
           <div class="col-sm-12">
               <div class="pagination">
                <span class="step-links">
                    {% if pj.has_previous %}
                        <a href="?page=1">&laquo;</a>
                        <a href="?page={{pj.previous_page_number }}">
                          <i class="fa fa-arrow-left" aria-hidden="true"></i>
                        </a>

                    {% endif %}

                    <span class="current">
                        Page {{pj.number }} of {{pj.paginator.num_pages }}.
                    </span>

                    {% if pj.has_next %}
                        <a href="?page={{pj.next_page_number }}">
                          <i class="fa fa-arrow-right" aria-hidden="true"></i>
                        </a>
                        <a href="?page={{pj.paginator.num_pages }}">&raquo;</a>
                    {% endif %}
                </span>
            </div>
           </div>
<!--__________________________________________________________________-->
       </div>
   </div>
</section>


{% include 'index/subscribe.html'%}
{% include 'index/partiners.html' %}

{% endblock %}

project/templates/projects/projects_detail.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section style="background:url({% static 'img/ddd.jpg'%});background-repeat: no-repeat;background-position: center center;
  background-size: cover;background-attachment: fixed;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="{% url 'projects:projects'%}">Projects</a>
          <a href="javascripts:void(0);">/</a>
          <a href="#">Project detail</a>
          <hr>
          <div class="item_category">
             <div >
                <a href="javascripts:void(0)">FILTER</a>
             </div>
             <div class="item_content p-4 rounded">
                <div class="row">
                    <div class="col-sm-12 col-lg-2">
                      <a href="{% url 'projects:projects2' 'Bazale'%}">Bazale</a>
                      <a href="{% url 'projects:projects2' 'Ulongwe'%}">Ulongwe</a>
                      <a href="{% url 'projects:projects2' 'Mpilisi'%}">Mpilisi</a>
                      <a href="{% url 'projects:projects2' 'Rivirivi'%}">Rivirivi</a>
                      <a href="{% url 'projects:projects2' 'Phalula'%}">Phalula</a>
                      
                </div>
                <div class="col-sm-12 col-lg-2">
                       <a href="{% url 'projects:projects2' 'Msamala'%}">Msamala</a>
                       <a href="{% url 'projects:projects2' 'Nkaya'%}">Nkaya</a>
                       <a href="{% url 'projects:projects2' 'Kachenga'%}">Kachenga</a>
                       <a href="{% url 'projects:projects2' 'Kachenga'%}">Chanthunya</a>
                       <a href="{% url 'projects:projects2' 'Kalembo'%}">Kalembo</a>
                    </div>

                    <div class="col-sm-12 col-lg-2">
                       <a href="{% url 'projects:projects2' 'Amidu'%}">Amidu</a>
                       <a href="{% url 'projects:projects2' 'Sawali'%}">Sawali</a>
                       <a href="{% url 'projects:projects2' 'Matola'%}">Matola</a>
                       <a href="{% url 'projects:projects2' 'Toleza'%}">Toleza</a>
                       <a href="{% url 'projects:projects2' 'Utale'%}">Utale</a>
                    </div>
                    <div class="col-sm-12 col-lg-4">
                       <h4 style="color:black;"><span>Almost </span>{{pj_count}} projects are being implemented in Balaka</h4>
                    </div>
                 </div>
             </div>
          </div>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>


<section class="my-4">
   <div class="container">
       <div class="row">
           <div class="col-sm-12 col-lg-8">
              <div class="p-2 rounded" style="background-color:#f2f2f2;">
                 <h4>{{pj}}</h4><hr>
                 {% if pj.image %}
                 <img src="{{pj.image.url}}" class="img-fluid">
                 {% else %}
                 <img src="{% static 'img/blk2.png' %}" class="img-fluid rounded">
                 {% endif %}
                <p>{{pj.body|safe}}</p>

                {% if pj.PJ_link %}
                <a id="custom_btn" href="{{pj.PJ_link}}">Learn more</a>
                {% endif%}

                {% if pj.docu %}
                <a href="{% url 'projects:pj_document_detail' pj.id %}">
                   <img src="{% static 'img/document.png'%}" height="30">
                </a>
                {% endif %}
              </div>
           </div>

           <div class="col-sm-12 col-lg-4">
               <div >
                  <h4>Other projects</h4><hr>
                  {% for pj in pj_d %}
                   <div class="p-2 rounded" style="background-color:#f2f2f2;">
                      <a href="{% url 'projects:PjDetail' pj.slug %}">
                         <img src="{{pj.image.url}}" class="img-fluid rounded">
                      </a>
                      <p>{{pj}}</p>
                   </div>
                  {% endfor %}
               </div>
           </div>
       </div>
   </div>
</section>


{% include 'index/subscribe.html'%}
{% include 'index/partiners.html' %}

{% endblock %}