BLK_DAESS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django .conf.urls. static import static
from django .conf import settings
#from myco import views
from django.views.static import serve
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("index.urls")),
    path('account/',include("account.urls")),
    path('event/',include('event.urls')),
    path('products/',include('products.urls')),
    path('donation/',include('donation.urls')),
    path('publications/',include('publications.urls')),
    path('achievement/',include('achievement.urls')),
    path('career/',include("career.urls")),
    path('project/',include("project.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
   
]

#handler404 = views.error_404
#handler500 = views.error_500


urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

career/urls.py
from . import views
from django.urls import path

app_name = "career"

urlpatterns = [
     
     path('job/',views.Job_list,name="job"),
     path('job_detail/<slug>/',views.job_detail,name="job_detail"),
     path('job_category/<cat>/',views.Job_list,name="job_category"),
     path('job_form/',views.job_form,name="job_form"),
     path('EditJob/<int:id>/',views.EditJob,name="EditJob"),
     path('remove_job/<int:id>/',views.remove_job,name="remove_job")  
]

event/urls.py
from . import views
from django.urls import path

app_name = "event"

urlpatterns = [
     path('event/',views.event,name="event"),
     path('eventasp/<asp>/',views.event,name="event2"),
     path('event_detail/<slug>/',views.event_detail,name="event_detail"),
     path('event_form/',views.event_form,name="event_form"),
     path('document_view/',views.document_view,name="document_view"),
     path('DocuForm/',views.DocuForm,name="DocuForm"),
     path('Editevent/<int:id>/',views.Editevent,name="Editevent"),
     path('RemoveEvent/<int:id>/',views.RemoveEvent,name="RemoveEvent"),
     path('document_detail/<int:id>/',views.document_detail,name="document_detail")  
]

index/urls.py
from . import views
from django.urls import path

app_name = "index"

urlpatterns = [
     
     path('',views.index,name="index"),
     path('about_daess/',views.about_daess,name="about_daess"),
     path('contact/',views.contact,name="contact"),
     path('DaessoBjectives/',views.daess_objectives,name="objective"),
     path('DaessStructure/',views.daess_structure,name="structure"),
     path('team/',views.team,name="team"),
     path('team2/<args>/',views.team,name="team2"),
     path('ASP/<asp>/',views.ASP,name="ASP"),
     path('Subscribe/',views.Subscribe,name="Subscribe"),
     path('unsubscribe/',views.unsubscribe,name="unsubscribe"),
     path('team_detail/<slug>/',views.tema_detail,name="tema_detail")
]

career/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import post_save,pre_save
from ckeditor.fields import RichTextField
from index.snipt import get_date,create_slug
from django.utils import timezone
import datetime


'''class PostManager(models.Manager):
	def get_query_set(self):
		now = datetime.datetime.now().date()
		return super(PostManager, self).get_query_set().filter(closing_date=now)'''

class job(models.Model):
	CATEGORY = (
		  ('Commission Based','Commission Based'),
		  ('Consultancy','Consultancy'),
		  ('Contract','Contract'),
		  ('Event','Event'),
		  ('Full Time','Full Time'),
		  ('Funding','Funding'),
		  ('Hourly Paid','Hourly Paid'),
		  ('International','International'),
		  ('Internship','Internship'),
		  ('Part Time','Part Time'),
		  ('Scholarship','Scholarship'),
		  ('Seasonal','Seasonal'),
		  ('Short-Term','Short-Term'),
		  ('Temporary','Temporary'),
		  ('Training','Training'),
		  ('Volunteer','Volunteer'),
		)
	user       = models.ForeignKey(User,null=True,blank=True,on_delete=models.CASCADE,related_name="job")
	orginisaton = models.CharField(max_length=100,blank=True)
	category = models.CharField(max_length=100,choices=CATEGORY)
	location = models.CharField(max_length=300)
	title = models.CharField(max_length=300)
	link  = models.URLField(blank=True,null=True)
	closing_date = models.DateField()
	body  = RichTextField()
	view  = models.PositiveIntegerField(default=0)
	slug  = models.SlugField(unique=True,null=True)
	date  = models.DateTimeField(auto_now_add=True)
	file  = models.ImageField(upload_to='logo',blank=True)
	created_at     = models.DateTimeField(auto_now_add=True)
	updated_at     = models.DateTimeField(auto_now=True)
	#CareerJob = PostManager()

	def __str__ (self):
		return self.title


	def whenpublished(self):

		post_date = get_date.post_time(self,self.created_at)
		return post_date

	def get_absolute_url(self):
		return reverse('career:job_detail',kwargs ={'slug':self.slug})


def create_slug(instance,new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = job.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.first().id)
        return create_slug(instance,new_slug=new_slug)
    return slug

def pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_receiver,sender=job)



class item_statistic(models.Model):#recommedation model
    item = models.ForeignKey(job,on_delete=models.CASCADE,related_name="daess_item")
    ip_address = models.CharField(blank=True,max_length=1000)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "views"

@receiver(post_save,sender=item_statistic)
def add_to_statistic(sender,created,instance,**kwargs):
    if created:
        instance.item.view += 1
        instance.item.save()

career/forms.py
from . models import job
from django.contrib.auth.models import User
from ckeditor.widgets import CKEditorWidget
from django.forms import ModelForm
from PIL import Image
from django import forms
	
class JobForm(ModelForm):

    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        body = forms.CharField(widget=CKEditorWidget())
        model = job
        fields = ('category',
                  'title',
                  'orginisaton',
                  'location',
                  'link',
                  'closing_date',
                  'body',
                  'file',
                  'x',
                  'y',
                  'width',
                  'height')
        labels ={'orginisaton':'Orginisaton name',
                  'link':'Web link (OPTIONAL)',
                  'file':'Logo',
                }
        widgets = {
            'closing_date': forms.TextInput(attrs={'placeholder': 'yyyy-mm-dd'}),
    
        }

    def save(self):
        photo = super(JobForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((400, 400), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

career/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse,JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from account.models import partners
from. forms import JobForm
from django.utils import timezone
import datetime
from index.snipt import ip_address
from . models import job,item_statistic


def Job_list(request,cat=None):

	context = {}
	context['search'] = "Search job"
	context['partners'] = partners.objects.all()

	if request.session.has_key('alert'):
		msg = request.session['alert']
		context['alert'] = msg 
		del request.session['alert']

	if cat:
		Job = job.objects.filter(category=cat).order_by('-updated_at')
		context['title'] = cat + " job"
	else:
		Job = job.objects.all().order_by('-updated_at')
		context['title'] = "Job list"

	if request.session.has_key('q'):
		quer = request.session['q']
		Job = Job.filter(Q(title__icontains=quer)|
		                 Q(orginisaton__icontains=quer)| 
		                 Q(closing_date__icontains=quer)|
		                 Q(category__icontains=quer)|
			             Q(location__icontains=quer)).distinct()
		del request.session['q']

	query =request.GET.get('q')
	if query:
		Job = Job.filter(Q(title__icontains=query)|
		                 Q(orginisaton__icontains=query)| 
		                 Q(closing_date__icontains=query)|
		                 Q(category__icontains=query)|
			             Q(location__icontains=query)).distinct()

	page = request.GET.get('page', 1)
	paginator = Paginator(Job,24)

	try:
		Job = paginator.page(page)
	except PageNotAnInteger:
		Job = paginator.page(1)
	except EmptyPage:
		Job = paginator.page(paginator.num_pages)

	context['job'] = Job

	return render(request,"career/job.html",context)

def job_detail(request,slug):
	context = {}
	context['title'] = "Job dtails"

	context['search'] = "Search job"

	context['partners'] = partners.objects.all()

	Job = job.objects.get(slug=slug)
	context['job'] = Job

	Job_view = job.objects.all().order_by('-view')[:10]
	context['jobView'] = Job_view

	item_statistic.objects.create(item=Job,ip_address=ip_address(request))

	query =request.GET.get('q')
	if query:
		request.session['q'] = query
		return redirect("career:job")

	return render(request,"career/job_detail.html",context)
	

@login_required(login_url="account:account")
def job_form(request):
	
	context = {}

	context['title'] = "Add job"

	context['search'] = "Search job"

	if request.method == "POST":
		form =JobForm(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save()
			instance.user = request.user
			instance.save()
			request.session["alert"] = "Job added successefully"
			return redirect('career:job')
	else:
		form = JobForm ()
	context['form'] = form

	return render(request,"index/form.html",context)


@login_required(login_url="account:account")
def EditJob(request,id):
	
	context = {}

	context['title'] = "edit job"

	context['search'] = "Search job"

	Job = job.objects.get(id=id)
	
	if request.method == "POST":
		form =JobForm(request.POST,request.FILES,instance=Job)
		if form.is_valid():
			instance = form.save()
			instance.user = request.user
			instance.save()
			request.session["alert"] = "Job edited successefully"
			return redirect('career:job')
	else:
		form = JobForm ()
	context['form'] = form

	return render(request,"index/form.html",context)



def remove_job(request,id):

	Job = job.objects.get(id=id)
	request.session['alert'] = "Job removed successefully"
	Job.delete()



	return redirect('career:job')

career/templates/career/job.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section style="background:url({% static 'img/career.jpg'%});background-repeat: no-repeat;background-position: center center;
  background-size: cover;background-attachment: fixed;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="{% url 'career:job' %}">Job</a>

          {% if cart %}
          <a href="javascripts:void(0);">/</a>
          <a href="#">{{cart}}</a>
          {% endif%}

          <hr>
          <div class="item_category">
             <div >
                <a href="javascript:void(0);">ALL CATEGORIES</a>
             </div>
             <div class="item_content p-4 rounded">
                <div class="row">
                     <div class="col-sm-12 col-lg-3">
                         <a href="{% url 'career:job_category' 'Consultancy' %}">Consultancy</a>
                         <a href="{% url 'career:job_category' 'Contract' %}">Contract</a>
                         <a href="{% url 'career:job_category' 'Event' %}">Event</a>
                         <a href="{% url 'career:job_category' 'Full Time' %}">
                          Full Time</a>
                         <a href="{% url 'career:job_category' 'Funding' %}">Funding</a> 
                     </div>
                     <div class="col-sm-12 col-lg-3">
                        
                         <a href="{% url 'career:job_category' 'Hourly Paid' %}">Hourly Paid</a>
                         <a href="{% url 'career:job_category' 'International' %}">International</a>
                         <a href="{% url 'career:job_category' 'Internship' %}">Internship</a>
                         <a href="{% url 'career:job_category' 'Part Time' %}">Part Time</a>
                         <a href="{% url 'career:job_category' 'Scholarship' %}">Scholarship</a>
                     </div>
                     <div class="col-sm-12 col-lg-3">
                         <a href="{% url 'career:job_category' 'Seasonal' %}">Seasonal</a>
                         <a href="{% url 'career:job_category' 'Short-Term' %}">Short-Term</a>
                         <a href="{% url 'career:job_category' 'Temporary' %}">Temporary</a>
                         <a href="{% url 'career:job_category' 'Training' %}">Training</a>
                         <a href="{% url 'career:job_category' 'Volunteer' %}">Volunteer</a>
                     </div>
                </div>
             </div>
          </div>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>

<section class="my-4">
    <div class="container">

        {% if alert %}
         <div id="alert" class="alert">
            <button type="button" data-dismiss="alert" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </button>
            <p style="color:rgb(0,128,0);">{{alert}}</p>
         </div>
        {% endif %}

         <div class="row">
             <div class="col-sm-12 col-lg-8">
                 {% for job in job %}
                 <div class="row p-3 rounded mb-2" id="job_list">
                     <div class="col-sm-2 col-lg-2">
                        {% if job.file %}
                        <img src="{{job.file.url}}" class="img-fluid">
                        {% else %}
                        <img src="{% static 'img/blk1.png' %}" class="img-fluid rounded">
                        {% endif %}
                     </div>

                     <div class="col-sm-10 col-lg-10">

                        <h4><a href="{% url 'career:job_detail' job.slug %}">{{job.title}}</a></h4>
                        <p><span class="p-1" id="job_cat">{{job.category}}</span> {{job.orginisaton}}</p>
                        <small>Posted {{job.whenpublished}}</small>
                     </div>
                 </div>
                 {% empty%}
                    <div class="col-sm-12 rounded" style="background-color:#f2f2f2;">
                      {% include 'index/error.html' %}
                   </div>
                 {% endfor %}
<!--________________________pagination_________________________________-->
           <div class="col-sm-12">
               <div class="pagination">
                <span class="step-links">
                    {% if job.has_previous %}
                        <a href="?page=1">&laquo;</a>
                        <a href="?page={{ job.previous_page_number }}">
                          <i class="fa fa-arrow-left" aria-hidden="true"></i>
                        </a>

                    {% endif %}

                    <span class="current">
                        Page {{job.number }} of {{job.paginator.num_pages }}.
                    </span>

                    {% if job.has_next %}
                        <a href="?page={{job.next_page_number }}">
                          <i class="fa fa-arrow-right" aria-hidden="true"></i>
                        </a>
                        <a href="?page={{job.paginator.num_pages }}">&raquo;</a>
                    {% endif %}
                </span>
            </div>
           </div>
<!--__________________________________________________________________-->
             </div>

             <div class="col-sm-12 col-lg-4">
               
             </div>

         </div>
    </div>
</section>

{% include 'index/subscribe.html'%}

{% if partners %}
<section class="pt-4 pb-4">
  <div class="container">
    <div class="text-center pb-4 div_header">
       <h4>Our Key Partners </h4>
   </div>
    <div class="owl-carousel text-center" id="item_list">
      {% for partners in partners %}
         <div>
            <a href="{{partners.link}}">
               <img src="{{partners.file.url}}" class="img-fluid" >
            </a>
         </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}

{% endblock %}

career/templates/career/job_detail.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section style="background:url({% static 'img/career.jpg'%});background-repeat: no-repeat;background-position: center center;
  background-size: cover;background-attachment: fixed;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="{% url 'career:job' %}">Job</a>
          <a href="javascripts:void(0);">/</a>
          <a href="#">Job detail</a>
          <hr>
          <div class="item_category">
             <div >
                <a href="javascript:void(0);">ALL CATEGORIES</a>
             </div>
             <div class="item_content p-4 rounded">
                  <div class="row">
                     <div class="col-sm-12 col-lg-3">
                         <a href="{% url 'career:job_category' 'Consultancy' %}">Consultancy</a>
                         <a href="{% url 'career:job_category' 'Contract' %}">Contract</a>
                         <a href="{% url 'career:job_category' 'Event' %}">Event</a>
                         <a href="{% url 'career:job_category' 'Full Time' %}">
                          Full Time</a>
                         <a href="{% url 'career:job_category' 'Funding' %}">Funding</a> 
                     </div>
                     <div class="col-sm-12 col-lg-3">
                        
                         <a href="{% url 'career:job_category' 'Hourly Paid' %}">Hourly Paid</a>
                         <a href="{% url 'career:job_category' 'International' %}">International</a>
                         <a href="{% url 'career:job_category' 'Internship' %}">Internship</a>
                         <a href="{% url 'career:job_category' 'Part Time' %}">Part Time</a>
                         <a href="{% url 'career:job_category' 'Scholarship' %}">Scholarship</a>
                     </div>
                     <div class="col-sm-12 col-lg-3">
                         <a href="{% url 'career:job_category' 'Seasonal' %}">Seasonal</a>
                         <a href="{% url 'career:job_category' 'Short-Term' %}">Short-Term</a>
                         <a href="{% url 'career:job_category' 'Temporary' %}">Temporary</a>
                         <a href="{% url 'career:job_category' 'Training' %}">Training</a>
                         <a href="{% url 'career:job_category' 'Volunteer' %}">Volunteer</a>
                     </div>
                </div>
             </div>
          </div>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>

<section class="my-4">
    <div class="container">
         <div class="row">
             <div class="col-sm-12 col-lg-8 ">
                <div class="p-2 rounded my-1" style="background-color:#f2f2f2;">

                   {% if request.user.is_authenticated %}
                     <div id="daess_edit">
                        <a href="{% url 'career:EditJob' job.id %}"><i class="fas fa-user-edit"></i></a>
                        <a href="{% url 'career:remove_job' job.id %}"><i class="fas fa-trash-alt"></i></a>
                     </div>
                  {% endif %}

                 <div class="row my-4" >
                     <div class="col-sm-12 col-lg-2">
                        {% if job.file %}
                        <img src="{{job.file.url}}" class="img-fluid">
                        {% else %}
                        <img src="{% static 'img/blk1.png' %}" class="img-fluid rounded">
                        {% endif %}
                     </div>
                     <div class="col-sm-12 col-lg-10">
                        <h4>{{job}}</h4>
                        <p>{{job.orginisaton}} 
                         <i class="fa fa-map-marker" aria-hidden="true"></i>
                         {{job.location}} <span class="p-1" id="job_cat">{{job.category}}</span></p>
                        <small>Posted {{job.whenpublished}}</small>
                     </div>
                 </div>
                 <div>
                    <hr>
                    <p>{{job.body|safe}}</p>
                    {% if job.link %}
                    <a href="{{job.link}}" id="custom_btn">Apply now</a>
                    {% endif %}
                    <hr>
                    <small style="color:red;">Clossing date {{job.closing_date}}</small>
                 </div>
                </div>
             </div>

             <div class="col-sm-12 col-lg-4">
                <div class="rounded p-2 my-1" style="background-color:#f2f2f2;">  <h4>Other Opportunities</h4><hr>
                   {% for job in jobView %}
                     <p>
                      <img src="{{job.file.url}}" height="64">
                      <a href="{% url 'career:job_detail' job.slug %}">{{job}}</a>
                    </p>
                   {% endfor %}
                </div>
             </div>
         </div>
    </div>
</section>

{% include 'index/subscribe.html'%}
{% include 'index/partiners.html' %}


{% endblock %}