BLK_DAESS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django .conf.urls. static import static
from django .conf import settings
#from myco import views
from django.views.static import serve
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("index.urls")),
    path('account/',include("account.urls")),
    path('event/',include('event.urls')),
    path('products/',include('products.urls')),
    path('donation/',include('donation.urls')),
    path('publications/',include('publications.urls')),
    path('achievement/',include('achievement.urls')),
    path('career/',include("career.urls")),
    path('project/',include("project.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
   
]

#handler404 = views.error_404
#handler500 = views.error_500


urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
     
     path('Login/',views.Login,name="account"),
     path('Logout/',views.Logout,name="logout"),
     path('dashboard/',views.dashboard,name="dashboard"),
     path('PartinersForm/',views.Partiners,name="Partiners"),
     path('Team/',views.teamMember,name="TeamMember"),
     path('editTeam/<slug>/',views.EditTeam,name="EditTeam"),
     path('removemember/<int:id>/',views.removemember,name="removemember"),
     #path('register_view/',views.register_view,name="register_view")
   
    
]

career/urls.py
from . import views
from django.urls import path

app_name = "career"

urlpatterns = [
     
     path('job/',views.Job_list,name="job"),
     path('job_detail/<slug>/',views.job_detail,name="job_detail"),
     path('job_category/<cat>/',views.Job_list,name="job_category"),
     path('job_form/',views.job_form,name="job_form"),
     path('EditJob/<int:id>/',views.EditJob,name="EditJob"),
     path('remove_job/<int:id>/',views.remove_job,name="remove_job")  
]

event/urls.py
from . import views
from django.urls import path

app_name = "event"

urlpatterns = [
     path('event/',views.event,name="event"),
     path('eventasp/<asp>/',views.event,name="event2"),
     path('event_detail/<slug>/',views.event_detail,name="event_detail"),
     path('event_form/',views.event_form,name="event_form"),
     path('document_view/',views.document_view,name="document_view"),
     path('DocuForm/',views.DocuForm,name="DocuForm"),
     path('Editevent/<int:id>/',views.Editevent,name="Editevent"),
     path('RemoveEvent/<int:id>/',views.RemoveEvent,name="RemoveEvent"),
     path('document_detail/<int:id>/',views.document_detail,name="document_detail")  
]

index/urls.py
from . import views
from django.urls import path

app_name = "index"

urlpatterns = [
     
     path('',views.index,name="index"),
     path('about_daess/',views.about_daess,name="about_daess"),
     path('contact/',views.contact,name="contact"),
     path('DaessoBjectives/',views.daess_objectives,name="objective"),
     path('DaessStructure/',views.daess_structure,name="structure"),
     path('team/',views.team,name="team"),
     path('team2/<args>/',views.team,name="team2"),
     path('ASP/<asp>/',views.ASP,name="ASP"),
     path('Subscribe/',views.Subscribe,name="Subscribe"),
     path('unsubscribe/',views.unsubscribe,name="unsubscribe"),
     path('team_detail/<slug>/',views.tema_detail,name="tema_detail")
]

project/urls.py
from . import views
from django.urls import path

app_name = "projects"

urlpatterns = [
     path('projects/',views.projects_view,name="projects"),
     path('projects2/<args>/',views.projects_view,name="projects2"),
     path('ProjectForm/',views.PjForm,name="PjForm"),
     path('PjDetail/<slug>/',views.PjDetail,name="PjDetail"),
     path('EditPj/<int:id>/',views.EditPj,name="EditPj"),
     path('removePj/<int:id>/',views.removePj,name="removePj"),
     path('pj_document_detail/<int:id>/',views.pj_document_detail,name="pj_document_detail")
]

index/templates/index/daess_objectives.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}


<section class="animatedParent"  style="background:url({% static 'img/banner9.jpg'%});background-repeat: no-repeat;background-position: center center;background-size:cover;background-attachment:fixed;height:90vh;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="{% url 'index:about_daess' %}">About DAESS</a>
          <a href="javascripts:void(0);">/</a>
          <a href="#">Objectives</a>
          <hr>
          <div id="banner_text1">
             <div>
                <h2 class="animated bounceInLeft" style="color:rgb(0,0,153);"><strong>Main objective</strong></h2>
                <h3 class="animated bounceInRight mb-4" style="color:white;"><strong >To empower farmers to demand high quality services from those that are best able to provide them.</strong></h3>

             </div>
             <div class="text-center animated bounceInDown" style="padding-top:20px;">
                <a class="" href="#daess">
                   <img src="{% static 'img/b_arrow.png' %}" height="50">
                </a>
             </div>
          </div>

           <div  id="banner_text2">
             <div>
                <h1 class="animated bounceInLeft" style="color:rgb(0,0,153);"><strong>Main objective</strong></h1>
                <h3 class="animated bounceInRight mb-4" style="color:white;font-size:70px;"><strong >To empower farmers to demand high quality services from those that are best able to provide them.</strong></h3>

             </div>
             <div class="text-center animated bounceInDown" style="padding-top:20px;">
                <a class="" href="#daess">
                   <img src="{% static 'img/b_arrow.png' %}" height="50">
                </a>
             </div>
          </div>
          {% include 'index/search.html' %}
      </div>
   </div>
</section>


<section class="pt-4 pb-4 my-4">
   <div class="container">
       <div class="text-center div_header pb-4 pt-4">
         <h4>Our main focal areas </h4>
      </div>
       <div class="row">
           <div class="col-sm-12 col-lg-2">
             
           </div>
           <div class="col-sm-12 col-lg-8 animatedParent text-center" data-sequence='500' id="focal_areas">
               <p class='animated fadeInRight' data-id='1'><strong>Organization of farmers demands:</strong> Farmers in their wealth & gender categories together identify priority agriculture felt needs & decide on action to undertake.</p>
               <p class='animated fadeInLeft' data-id='2'><strong>Organizing service providers’ response to farmers’ needs:</strong> identifying and engaging service providers that would respond to farmers’ needs.</p>
                <p class='animated fadeInRight' data-id='3'><strong>Stakeholders Coordination, collaboration and co-location:</strong> Service providers can support famers’ needs as an individual organization or in collaboration with other stakeholders.</p>
                <p class='animated fadeInLeft' data-id='4'><strong>Funding acquisition:</strong> district council will have to find ways of financing agricultural extension services from a diverse source of funds existing in the  districts</p>
           </div>
       </div>
   </div>
</section>

<section class="p-4 animatedParent" style="background-color:#f2f2f2;"><a name="daess"></a>
   <div class="container" id="objectives">

      <div class="text-center div_header pb-4 pt-4">
         <h4>Other objectives</h4>
      </div>
      <div class="row" id="objectives2">

          <div class="col-sm-12 col-lg-6">
             <div id="objectives3" class='p-2 rounded my-1 animated fadeInRight' data-id='1'>
                <p class=""><span style="font-size:30px;">T</span>o mobilise service providers as value chain players to collectively or individually respond to farmers’ prioritised agricultural needs.</p>
             </div>
          </div>

          <div class="col-sm-12 col-lg-6">
             <div id="objectives3" class='p-2 rounded my-1 animated fadeInLeft' data-id='2'>
                <p class=""><span style="font-size:30px;">T</span>o instil sense of ownership and self-reliance amongst farmers whilst undertaking agricultural programmes.</p>
             </div>
          </div>

          <div class="col-sm-12 col-lg-6">
             <div id="objectives3" class='p-2 rounded my-1 animated fadeInRight' data-id='3'>
                 <p class=""><span style="font-size:30px;">T</span>o provide platform for farmers to discuss and mutually agree on common agricultural needs to be addressed by themselves and those that may require assistance from elsewhere.</p>
             </div>
          </div>

          <div class="col-sm-12 col-lg-6">
             <div id="objectives3" class='p-2 rounded my-1 animated fadeInLeft' data-id='4'>
                <p class=""> <span style="font-size:30px;">T</span>o enhance coordination, collaboration and co-location amongst stakeholders in provision of agricultural extension and advisory services. </p>
             </div>
          </div>
      

      </div>
   </div>
</section>

{% include 'index/team2.html'%}
{% include 'index/subscribe.html'%}
{% include 'index/partiners.html' %}


{% endblock %}

index/templates/index/error.html
{% load static %}

<div class="text-center mt-4" style="padding-top:100px;padding-bottom:200px;">
	<h1 style="color:green;"><strong>404</strong></h1>
   <p><strong>Error - Not Found</strong></p>
 
   <p>Sorrey We’re not able to find what you looking for</p>
</div>

index/templates/index/footer.html
{% load static %}

<section class="mt" id="footer" 
         style="background:rgb(0,0,153);">
	<div class="container">
		 <div class="row">
		 	  <div class="col-sm-12 col-lg-4">
		 	  	  <div class="text-center p-2">
		 	  	  	 <h4>BALAKA DAESS</h4>
		 	  	  </div>
		 	  	  <div class="p-2">
		 	  	  	 <p class="text-justify ">District Agricultural Extension Services System (DAESS) is a decentralized extension system that seeks to enhance collaboration and coordination of service providers in agricultural extension and advisory services in order to promote harmonization and integration in service provision</p> 
		 	  	  </div>
		 	  </div>
		 	  <div class="col-sm-12 col-lg-6">
		 	  	  <div class="text-center p-2">
		 	  	  	 <h4>QUICK SEARCH</h4>
		 	  	  </div>

		 	  	  <div class="row rounded p-2" style="border:1px solid white;">

		 	  	        <div class="col-sm-12 col-lg-4" id="footer_menu">
		 	  	            <a href="{% url 'products:products' %}">Products</a>
		 	  	            <a href="{% url 'event:event' %}">Upcoming event</a>
		 	  	            <a href="{% url 'achievement:achievement' %}">Success stories</a>
		 	  	            <a href="{% url 'event:document_view' %}">Documents</a>
		 		            <a href="http://bit.do/DAECC-Balaka ">Dropbox</a>
		 	  	            <a href="{% url 'career:job' %}">Career</a>
		 	  	            <a href="{% url 'projects:projects' %}">Projects</a>
		 	  	            <a href="{% url 'index:contact' %}">Contact</a>
		 	            </div>

		 	            <div class="col-sm-12 col-lg-4" id="footer_menu">   <a href="{% url 'publications:videos2' 'Agricuture Extension video' %}">Agricuture videos</a>
		 	            	<a href="{% url 'publications:videos2' 'Nutrition Extension videos' %}">Nutrition videos</a>
		 	            	<a href="{% url 'publications:videos2' 'Documentary' %}">Documentary</a>
		 	  	            <a href="{% url 'index:ASP' 'Msamala ASP'%}">Msamala ASP</a>
                            <a href="{% url 'index:ASP' 'Nkaya ASP'%}">Nkaya ASP</a>
                            <a href="{% url 'index:ASP' 'Kachenga ASP'%}">Kachenga ASP</a>
                           <a href="{% url 'index:ASP' 'Chanthunya ASP'%}">Chanthunya ASP</a>
                           <a href="{% url 'index:ASP' 'Kalembo ASP'%}">Kalembo ASP</a>
		 	            </div>
		 	            
		 	            <div class="col-sm-12 col-lg-4" id="footer_menu">
		 	  	            <a href="{% url 'index:ASP' 'Amidu ASP'%}">Amidu ASP</a>
                            <a href="{% url 'index:ASP' 'Sawali ASP'%}">Sawali ASP</a>
                            <a href="{% url 'index:ASP' 'Matola ASP'%}">Matola ASP</a>
                            <a href="{% url 'index:ASP' 'Phalula ASP'%}">Phalula ASP</a>
                            <a href="{% url 'index:ASP' 'Toleza ASP'%}">Toleza ASP</a>
                            <a href="{% url 'index:team2' 'DAC'%}">DAC Team</a>
                            <a href="{% url 'index:team2' 'DAECC'%}">DAECC Team</a>
                            <a href="{% url 'index:team2' 'DSP'%}">DSP Team</a>
		 	            </div>

		 	  	</div>
		 	</div>
		 	
		 	<div class="col-sm-12 col-lg-2 p-2 text-center">

		 		 <div class="text-center p-2">
		 		 	<h4>GIVE A HAND</h4>
		 		 </div>

		 	  	 <div class="p-2">
		 	  	 	<div class="my-4">
		 	  	 		<img src="{% static 'img/donate.png'%}" height="100">
		 	  	 	</div>
		            <a href="{%url 'give:donation'%}" style="border:1px solid white;" class="mt-2 rounded" id="custom_btn">Donate now</a>
		 	  	 </div>

		 	</div>
		 	<div class="col-sm-12 mt-4 text-center">
		 		 <div >
		 		 	<h4>Payment methods</h4>
		 		 </div>
		 		 <a href="https://www.paypal.com/us/home">
		 		 	<img src="{% static 'img/paypal.jpg' %}" class="rounded" height="46">
		 		 </a>
		 		 <a href="https://www.tnm.co.mw/#/">
		 		 	<img src="{% static 'img/mpamba.jpg' %}" class="rounded" height="46">
		 		 </a>
		 		 <a href="https://www.recharge.com/en/malawi/airtel-top-up?gclid=Cj0KCQiA0ZHwBRCRARIsAK0Tr-pWnkev9Uzzc5sliskBZz_0sLQUaPib3_7E1Kn5NVCI-xOMV_cDkCYaAotxEALw_wcB">
		 		 	<img src="{% static 'img/airtelmoney.jpg' %}" class="rounded" height="46">
		 		 </a>
		 	</div><hr>
		</div>
	</div>

	<div class="container">
		<div class="btn-group p-2 my-1 ml-0" role="group" aria-label="daess">
  

       <div class="fb-share-button mt-0 mx-2" data-href="{{request.build_absolute_uri }}" data-layout="button_count" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a>
      </div>

      <div>
      <a class="twitter-share-button mt-2" href="https://twitter.com/intent/tweet?text=Hello%20world"data-size="large">
        Tweet
     </a>
      </div>

       <div class="ml-4">
    	<a style="color:white;" href="javascripts:void(0);">Terms and Conditions</a> |
    	<a style="color:white;" href="javascripts:void(0);">Privacy Policy</a>
    </div>


      
</div>
    
	</div>

	<div class="text-center my-4">
		<p>© 2019 Balaka DAESS. All Rights Reserved</p>
	</div>
</section>

index/templates/index/header.html
{% load static %}
<div class="p-2 mb-4" id="top_search" >
	<div class="">
		<a id="Search_btn" href="javascript:void(0);">
		 	<i class="fa fa-search" aria-hidden="true"></i>
		</a>
		<a class="donate_btn2 p-1 rounded" href="{%url 'give:donation'%}">
		Donate now</a>
	</div>
</div>
<section id="top_header" style="background:rgb(0,0,153);">
	<div class="container">
		<a class="co" href="jascript:void(0);">
		<i class="fa fa-phone" aria-hidden="true"></i>
		+(265) 01-552-020/048</a>
		<a class="co" href="jascript:void(0);">
		<i class="fa fa-fax" aria-hidden="true"></i>
		Fax +(265) 1-552-020</a>
		

        <div class="ml-4" id="donate_btn">
			<a href="{%url 'give:donation'%}">Donate now</a>
		</div>

		<div style="float:right;">
			{% if request.user.is_authenticated %}
			 <div class="logout">
			 	<a href="">
			 	<i class="fa fa-user" aria-hidden="true"></i>
			 	My account</a>
			 	<div class="daess_account rounded-bottom">
			 		<a href="{% url 'account:dashboard' %}">Dashboard</a>
			 		<a href="{% url 'account:logout' %}">
			 		Logout</a>
			 	</div>
			 </div>
			{% else%}
			<a href="{% url 'account:account'%}">
			<i class="fa fa-sign-in" aria-hidden="true"></i>
			Login</a>
			{% endif %}

		</div>
		
	</div>
</section>


<section id="nav_bar" style="background:rgb(0,0,153);">
	<div class="container rounded-top" id="inner_nav">
	     <a href="javascript:void(0);">
	     	<img src="{% static 'img/daess.png'%}" height="40">
	     </a> 

	     <div class="nav_item pt-1">
		 	<a id="Search_btn3" href="javascript:void(0);">
		 		<i class="fa fa-search" aria-hidden="true"></i>
		 	</a>
		 </div>

	     <div class="nav_item">
		 	<a href="{% url 'index:contact' %}">Contact</a>
		 </div>

		 <div class="nav_item">
		 	<a href="{% url 'projects:projects' %}">Projects</a>
		 </div>
		 <div class="nav_item">
		 	<a href="javascript:void(0);">Stay informed
		 		<i class="fa fa-caret-down" aria-hidden="true"></i>
		 	</a>
		 	<div class="nav_content nav2 rounded-bottom">
		 		<a href="{% url 'event:event' %}">Upcoming events</a>
		 		<a href="{% url 'achievement:achievement' %}">Success stories</a>
		 		<a href="{% url 'publications:videos'%}">Extension videos</a>
		 		<a href="{% url 'event:document_view' %}">Documents</a>
		 		<a href="http://bit.do/DAECC-Balaka ">Dropbox</a>
		 	</div>
		 </div>
		 
		 <div class="nav_item">
		 	<a href="{% url 'career:job' %}">Careers</a>
		 </div>
		 <div class="nav_item">
		 	<a href="{% url 'products:products' %}">Products</a>
		 </div>
		 <div class="nav_item">
		 	<a href="javascript:void(0);">
		 	About DAESS
		 	<i class="fa fa-caret-down" aria-hidden="true"></i>
		 </a>
		 	<div class="nav_content rounded-bottom">
		 		<a href="{% url 'index:about_daess' %}">About Balaka DAESS</a>
		 		<a href="{% url 'index:objective' %}">Objectives</a>
		 		<a href="{% url 'index:structure'%}">Structure</a>
		 		<a href="{% url 'index:team'%}">Team</a>
		 	</div>
		 </div>
		 
		 <div class="nav_item">
		 	<a href="{% url 'index:index' %}">Home</a>
		 </div>
		 <div id="menu">
		 	<a href="javascript:void(0);" id="menu_btn">
		 		<i class="fa fa-bars" aria-hidden="true"></i>
		 	</a>
		 </div>
	</div>
</section>

<!------------------min navbar------------------------------->
<section class="min_navbar p-2">
	<a href="javascript:void(0);" class="close" id="menu_btn2" style="color:white;">
		<i class="fa fa-times" aria-hidden="true"></i>
    </a>
	<div class="mx-4 p-3">
		<div class="nav_item2">
		 	<a href="{% url 'index:index' %}">Home</a>
		</div>

		<div class="nav_item2">
		 	<a href="javascript:void(0);">About DAESS
		 		<i class="fa fa-caret-down" aria-hidden="true"></i>
		 	</a>
		 	<div class="nav_content rounded-bottom">
		 		<a href="{% url 'index:about_daess' %}">About Balaka DAESS</a>
		 		<a href="{% url 'index:objective' %}">Objectives</a>
		 		<a href="{% url 'index:structure'%}">Structure</a>
		 		<a href="{% url 'index:team'%}">Team</a>
		 	</div>
		</div>

		<div class="nav_item2">
		 	<a href="{% url 'products:products' %}">Products</a>
		</div>

		<div class="nav_item2">
		 	<a href="javascript:void(0);">Stay informed
		 		<i class="fa fa-caret-down" aria-hidden="true"></i>
		 	</a>
		 	<div class="nav_content rounded-bottom">
		 		<a href="{% url 'event:event' %}">Upcoming events</a>
		 		<a href="{% url 'achievement:achievement' %}">Success stories</a>
		 		<a href="{% url 'publications:videos'%}">Extension videos</a>
		 		<a href="{% url 'event:document_view' %}">Documents</a>
		 		<a href="http://bit.do/DAECC-Balaka ">Dropbox</a>
		 	</div>
		 </div>

		 <div class="nav_item2">
		 	<a href="{% url 'career:job' %}">Careers</a>
		 </div>

		 <div class="nav_item2">
		 	<a href="{% url 'projects:projects' %}">Projects</a>
		 </div>

		 <div class="nav_item2">
		 	<a href="{% url 'index:contact' %}">Contact</a>
		 </div>

		 <div >
			{% if request.user.is_authenticated %}

			 	<div class="nav_item2">
			 		<a href="{% url 'account:dashboard' %}">Dashboard</a>
			 	</div>

			 	<div class="nav_item2">
			 		<a href="{% url 'account:logout' %}">
			 		Logout</a>
			 	</div>
			 
			{% else%}
			 <div class="nav_item2">
			 	 <a href="{% url 'account:account'%}">
			        <i class="fa fa-sign-in" aria-hidden="true"></i>
			        Login
			     </a>
			 </div>
			{% endif %}

		</div>
	
	</div>
</section>

index/templates/index/team.html
{% extends "index/base.html"%}
{% load static %}


    
{% block body %}

<section style="background:url({% static 'img/ddd.jpg'%});background-repeat: no-repeat;background-position: center center;
  background-size: cover;background-attachment: fixed;">
   <div class="container">
      <div class="p-4 page_header">
          <a href="{% url 'index:index' %}">
           Home
           
          </a> 
          <a href="javascripts:void(0);">/</a>
          <a href="{% url 'index:about_daess' %}">About DAESS</a>
          <a href="javascripts:void(0);">/</a>
          <a href="{% url 'index:objective' %}">Objectives</a>
          <a href="javascripts:void(0);">/</a>
          <a href="{% url 'index:structure'%}">Sturcture</a>
          <a href="javascripts:void(0);">/</a>
          <a href="#">Team</a>
          <hr>
          <div class="item_category">
             <div >
                <a href="javascripts:void(0)">TEAM</a>
             </div>
             <div class="item_content p-4 rounded">
                <div class="row">
                    <div class="col-sm-12 col-lg-4">
                       <a href="{% url 'index:team2' 'DAC'%}">DAC</a>
                       <a href="{% url 'index:team2' 'DAECC'%}">DAECC</a>
                       <a href="{% url 'index:team2' 'DSP'%}">DSP</a>
                    </div>

                    <div class="col-sm-12 col-lg-4">
                       <a href="{% url 'index:team2' 'Msamala ASP'%}">Msamala ASP</a>
                       <a href="{% url 'index:team2' 'Nkaya ASP'%}">Nkaya ASP</a>
                       <a href="{% url 'index:team2' 'Kachenga ASP'%}">Kachenga ASP</a>
                       <a href="{% url 'index:team2' 'Chanthunya ASP'%}">Chanthunya ASP</a>
                       <a href="{% url 'index:team2' 'Kalembo ASP'%}">Kalembo ASP</a>
                    </div>

                    <div class="col-sm-12 col-lg-4">
                       <a href="{% url 'index:team2' 'Amidu ASP'%}">Amidu ASP</a>
                       <a href="{% url 'index:team2' 'Sawali ASP'%}">Sawali ASP</a>
                       <a href="{% url 'index:team2' 'Matola ASP'%}">Matola ASP</a>
                       <a href="{% url 'index:team2' 'Phalula ASP'%}">Phalula ASP</a>
                       <a href="{% url 'index:team2' 'Toleza ASP'%}">Toleza ASP</a>
                    
                    </div>
                 
                </div>
             </div>
          </div>
          {% include 'index/search.html' %}
      </div>
   </div>

</section>


<!----------------key partners section--------------->
<section class="pt-4 pb-4" >
  <div class="container">
    {% if alert %}
         <div id="alert" class="alert">
            <button type="button" data-dismiss="alert" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </button>
            <p style="color:rgb(0,128,0);">{{alert}}</p>
         </div>
        {% endif %}
    <div class="text-center pb-4 div_header">

       {% if team %}
       <h4>{{team}} Team</h4>
       {% else %}
       <h4>Team</h4>
       {% endif %}

   </div>
    <div class="row text-center">
      {% for contact in contact %}
                <div class="col-sm-12 col-lg-3">
         <div class="p-2 rounded teammember my-2" id="teammember">
            
               <h4 style="color:white;"><strong>{{contact.name}}</strong></h4>
               {% if contact.file %}
               <img src="{{contact.file.url}}" class="img-fluid rounded-circle">
               {% else %}
               <img src="{% static 'img/blk1.png' %}" class="img-fluid rounded-circle">
               {% endif %}
               <p>{{contact.position}}</p>

                  <div class="text-center">

                    {% if contact.facebook %}
                    <a class="mr-4" href="{{contact.facebook}}"><i class="fab fa-facebook-f"></i></a>
                    {% else %}
                    <a class="mr-4" href="javascript:void(0);"><i class="fab fa-facebook-f"></i></a>
                    {% endif %}

                    {% if contact.linkedin %}
                       <a class="mr-4" href="{{contact.linkedin}}"><i class="fab fa-linkedin-in"></i></a>
                    {% else %}
                       <a class="mr-4" href="javascript:void(0);"><i class="fab fa-linkedin-in"></i></a>
                    {% endif %}

               </div>
               

              <div class="rounded inner_teammember" id="inner_teammember">


                  {% if request.user.is_authenticated %}
                     <div id="daess_edit">
                        <a href="{% url 'account:EditTeam' contact.slug %}"><i class="fas fa-user-edit"></i></a>
                        <a href="{% url 'account:removemember' contact.id %}"><i class="fas fa-trash-alt"></i></a>
                     </div>
                  {% endif %}

                  <h4 style="color:white;"><strong>{{contact.name}}</strong></h4>
                  <img src="{{contact.file.url}}" class="img-fluid rounded-circle">
                  <a href="{% url 'index:tema_detail' contact.slug %}">Chat with me</a>

                  <div class="text-center">

                    {% if contact.facebook %}
                    <a class="mr-4" href="{{contact.facebook}}"><i class="fab fa-facebook-f"></i></a>
                    {% else %}
                    <a class="mr-4" href="javascript:void(0);"><i class="fab fa-facebook-f"></i></a>
                    {% endif %}

                    {% if contact.linkedin %}
                       <a class="mr-4" href="{{contact.linkedin}}"><i class="fab fa-linkedin-in"></i></a>
                    {% else %}
                       <a class="mr-4" href="javascript:void(0);"><i class="fab fa-linkedin-in"></i></a>
                    {% endif %}

                    <a href="{% url 'index:tema_detail' contact.slug %}"><i class="fab fa-whatsapp"></i></a>
                    </div>
               </div>
           
         </div>
       </div>
      {% empty %}
        <div class="col-sm-12 col-lg-12 text-center">
           {% include 'index/error.html'%}
        </div>
      {% endfor %}

      <!--_______________________pagination_________________________________-->
           <div class="col-sm-12">
               <div class="pagination">
                <span class="step-links">
                    {% if contact.has_previous %}
                        <a href="?page=1">&laquo;</a>
                        <a href="?page={{contact.previous_page_number }}">
                          <i class="fa fa-arrow-left" aria-hidden="true"></i>
                        </a>

                    {% endif %}

                    <span class="current">
                        Page {{contact.number }} of {{contact.paginator.num_pages }}.
                    </span>

                    {% if contact.has_next %}
                        <a href="?page={{contact.next_page_number }}">
                          <i class="fa fa-arrow-right" aria-hidden="true"></i>
                        </a>
                        <a href="?page={{contact.paginator.num_pages }}">&raquo;</a>
                    {% endif %}
                </span>
            </div>
           </div>
<!--__________________________________________________________________-->
    </div>
  </div>

</section>


{% include 'index/subscribe.html'%}
{% include 'index/partiners.html' %}


{% endblock %}